export const LOGIN_USER = 'login_user';
export const REGISTER_USER = 'register_user';
export const AUTH_USER = 'auth_user';
export const SET_LOADING = 'set_loading';
export const SET_ERROR = 'set_error';
export const SET_BUY = 'set_buy';
export const SET_STORE = 'set_store';
export const ADD_ITEM = 'add_item'; // 장바구니 추가
export const DELETE_ITEM = 'delete_item'; // 장바구니 삭제
export const INCREMENT = 'increment'; // 장바구니에서 수량 증가
export const DECREMENT = 'decrement'; // 장바구니에서 수량 삭제
